#!/usr/bin/env python3
"""gen_prelude.py <amu>/src/kotoba/compiler/refactor/prelude.cljk > lang/compat/kotoba/compiler/refactor/prelude.kotoba
The twin's strings are the host's, byte for byte (the host prelude has no escape in its strings; this refuses one)."""
import re, sys
src = open(sys.argv[1], encoding='utf-8').read()
def strings(region):
    out, i = [], 0
    while i < len(region):
        c = region[i]
        if c == ';':
            i = region.index('\n', i) if '\n' in region[i:] else len(region); continue
        if c == '"':
            j = region.index('"', i + 1); s = region[i + 1:j]
            assert '\\' not in s, 'escape in prelude string'
            out.append(s); i = j + 1; continue
        i += 1
    return out
d0 = src.index('(def defs'); o0 = src.index('(def order')
defs = strings(src[d0 + len('(def defs'):o0]); order = strings(src[o0 + len('(def order'):])
names, texts = defs[0::2], defs[1::2]
assert len(defs) % 2 == 0 and names == order, (names, order)
head = ''';; kotoba.compiler.refactor.prelude -- the GUEST-ROUTE twin of amu's `src/kotoba/compiler/refactor/prelude.cljk`
;; (GENERATED by scripts/refactor-twin-diff/gen_prelude.py from the host file; do not edit by hand).
;;
;; The host module is two vars: `defs` (a map from helper name to the text of its definition) and `order` (the names in
;; insertion order). A map of strings has no exported Kotoba spelling, and a module with no export is refused (seed E6009),
;; so the twin is the same data behind two functions:
;;   (order)        -> [:list :string]   the host's `order`
;;   (text-of name) -> :string           the host's `(get defs name)`; "" for a name that is not a helper
;;   (has? name)    -> :bool             the host's `(contains? defs name)`
;; The texts are the host's, byte for byte (they are the Kotoba/host `#?` readings amu inserts into a rewritten source).

(ns kotoba.compiler.refactor.prelude
  (:export [order text-of has?]))

'''
q = lambda s: '"' + s + '"'
body = '(defn order [] [:list :string]\n  (typed-list-new [:list :string] ' + ' '.join(q(n) for n in order) + '))\n\n'
body += '(defn text-of [name :string] :string\n  (cond\n' + ''.join(f'    (string=? name {q(n)})\n    {q(t)}\n' for n, t in zip(names, texts)) + '    :else ""))\n\n'
body += '(defn has? [name :string] :bool\n  (or ' + ' '.join(f'(string=? name {q(n)})' for n in names) + '))\n'
sys.stdout.write(head + body)
