#!/usr/bin/env nbb
;; gen-parity-harness.cljs -- the Clojure side of a whole-component acceptance,
;; derived from the oracle rather than adapted from a sibling by hand.
;;
;; Measured 2026-09-11 across the wave-1 cohort: all twenty pilots carry a
;; whole-component build, nineteen carry a migration record, and FOUR carry a
;; parity harness. A component that was built and never compared against the
;; oracle it replaces is in the state com-abb-robotics' own record called
;; :not-claimed -- the oracle functions were run, and never checked against
;; anything.
;;
;; WHAT IT EMITS, AND WHY ONLY THIS MUCH
;;
;; Only the layers that are derivable from the oracle without a judgement call:
;;
;;   route count   (count m/routes)
;;   as-int        over the shared fixture-text table
;;   as-bool       over the same table
;;   page-limit    every pilot sampled declares [requested]
;;
;; `fixture-text` is byte-identical in all four hand-written harnesses (sha
;; 3ae1d6b0), so it is a constant here rather than something to derive.
;;
;; It does NOT emit the store, filter, pagination, handler or expand layers.
;; Those need fixtures shaped to the repository's own entities, and the four
;; hand-written harnesses disagree about them -- 20 sections in com-aadhaar, 11
;; in com-abb-robotics. Generating a guess there would produce arms that run
;; without asserting anything about this repository, which is the failure the
;; component generator already had to be taught not to commit.
;;
;;   nbb gen-parity-harness.cljs <repo-dir> <src-dir-name>
;;
;; exit 0  wrote the harness
;; exit 2  REFUSED -- no oracle, or it does not expose what the harness calls

(ns gen-parity-harness
  (:require [clojure.string :as str]
            ["fs" :as fs]
            ["path" :as path]))

(def argv (vec (remove #(str/ends-with? % ".cljs") (drop 2 (js->clj js/process.argv)))))

(defn refuse! [msg data]
  (println (str "REFUSED\t" msg "\t" (pr-str data)))
  (.exit js/process 2))

(def required-vars
  "Every var the emitted harness calls. Checked before writing, because a
  harness that cannot load is worse than no harness: it fails at the point of
  use, long after the run that produced it looked successful."
  ["routes" "as-int" "as-bool" "page-limit" "entity-specs" "fresh-store" "persist!" "query" "retract!"])

(defn harness [ns-name]
  (str
   "(ns q9-oracle\n"
   "  \"The Clojure side of the whole-component acceptance: run `" ns-name "` under\n"
   "   nbb and print the same numbers the aarch64 artifact prints.\n\n"
   "     nbb --classpath src:<kotoba-lang/text>/src q9-oracle.cljs\n\n"
   "   GENERATED by scripts/gen-parity-harness.cljs. Only the layers that are\n"
   "   derivable from the oracle without a judgement call are here: the route\n"
   "   count, and as-int / as-bool / page-limit over the shared fixture table.\n"
   "   The store, filter, pagination, handler and expand layers need fixtures\n"
   "   shaped to this repository's entities and are NOT generated -- an arm that\n"
   "   runs without asserting anything about this repository is worse than an\n"
   "   absent one.\n\n"
   "   ## The control\n\n"
   "   `as-int` of \\\"12abc\\\" MUST differ between this harness and the artifact.\n"
   "   The oracle's as-int is a reader conditional whose branches disagree: the\n"
   "   :cljs branch is js/parseInt and yields 12, the :clj branch is\n"
   "   Long/parseLong which throws and yields 0, and the component matches :clj.\n"
   "   Measured across the cohort and recorded in kotoba-lang\n"
   "   lang/q9-wave1-tranche-1.edn.\n\n"
   "   So a run of this harness under nbb in which EVERYTHING matches has not\n"
   "   demonstrated that it can detect a mismatch, and is not a pass. A run on a\n"
   "   JVM would legitimately agree on that row; say which runtime produced any\n"
   "   result.\"\n"
   "  (:require [" ns-name " :as m]\n            [clojure.string :as str]))\n\n"
   ";; Byte-identical in every hand-written harness in this cohort.\n"
   "(def fixture-text\n"
   "  {0 \"12\" 1 \" 42 \" 2 \"-7\" 3 \"12abc\" 4 \"\" 5 \"true\" 6 \"TRUE\" 7 \"Yes\" 8 \"on\"\n"
   "   9 \"1\" 10 \"0\" 11 \"false\" 12 \"null\" 13 \"nope\"})\n\n"
   ";; The same rolling hash the .kotoba computes: acc*131 + code point, mod\n"
   ";; 1000000007, seeded 7. Every intermediate stays under 2^53, so a JS double\n"
   ";; holds it exactly.\n"
   "(defn str-hash [x]\n"
   "  (reduce (fn [acc ch] (mod (+ (* acc 131) (.charCodeAt ch 0)) 1000000007)) 7 (seq (str x))))\n\n"
   ";; The entity table, rendered the way `oracle-table` renders it. Unlike the\n"
   ";; layers above, this one is DERIVED FROM THIS REPOSITORY'S OWN SPEC TABLE on\n"
   ";; both sides, so it is the first row here that carries a per-repository\n"
   ";; signal rather than a cohort-wide constant. It is also a runtime check for\n"
   ";; the defect the component generator's evidence floor exists to catch: a\n"
   ";; component whose tables still answer the TEMPLATE's prefixes passes\n"
   ";; `amu check`, and fails here.\n"
   "(defn coerce-csv [spec]\n"
   "  (str/join \",\" (map (fn [[k v]] (str (name k) \":\" (name v))) (:coerce spec))))\n\n"
   "(defn table-line [spec]\n"
   "  (str/join \"|\" [(:entity spec) (:plural spec) (:id-prefix spec)\n"
   "                 (str/join \",\" (map name (:fields spec)))\n"
   "                 (str/join \",\" (map name (:required spec)))\n"
   "                 (coerce-csv spec)]))\n\n"
   "(defn row [label v] (println (str label \"\\t\" v)))\n\n"
   "(println \"; oracle = " ns-name " under nbb\")\n"
   "(row \"main(route-count)\" (count m/routes))\n\n"
   "(println \"; as-int\")\n"
   "(doseq [i [0 1 2 3 4 12]] (row (str \"as-int \" i) (m/as-int (fixture-text i))))\n\n"
   "(println \"; as-bool\")\n"
   "(doseq [i [5 6 7 8 9 10 11 4 13]]\n"
   "  (row (str \"as-bool \" i) (if (m/as-bool (fixture-text i)) 1 0)))\n\n"
   "(println \"; page-limit\")\n"
   "(doseq [r [-5 0 1 20 99 100 101 250]] (row (str \"page-limit \" r) (m/page-limit r)))\n\n"
   ";; --- the store, as COUNTS only -------------------------------------------\n"
   ";;\n"
   ";; This is the first fixture-shaped layer the generator emits, and it emits\n"
   ";; only part of one. `oracle-store` in the component has eight selectors: five\n"
   ";; return `arr-count` and three return `str-hash` of a rendered store. The\n"
   ";; counts are compared here; the hashes are not, because they hash the\n"
   ";; component's own JSON convention and a disagreement would confound\n"
   ";; behaviour with layout.\n"
   ";;\n"
   ";; The seeded row is DERIVED, not invented: the component's own `seeded-row`\n"
   ";; is generated from the spec table -- id prefix, one non-required field, then\n"
   ";; the required ones -- so mirroring it here reads the same source rather than\n"
   ";; constructing a new input. That is the distinction that kept this layer out\n"
   ";; until now.\n"
   ";;\n"
   ";; What it actually tests is persistence SEMANTICS, which no earlier layer\n"
   ";; touches: does retracting an absent id leave the count alone, and does\n"
   ";; putting an existing id replace rather than append.\n"
   "(def root-spec\n"
   "  (or (first (filter #(empty? (:refs %)) m/entity-specs)) (first m/entity-specs)))\n\n"
   "(def other-spec\n"
   "  (or (first (remove #(= (:entity %) (:entity root-spec)) m/entity-specs)) root-spec))\n\n"
   "(defn seeded-row [i]\n"
   "  (let [req (map name (:required root-spec))\n"
   "        extra (first (remove (set req) (map name (:fields root-spec))))]\n"
   "    (merge {:id (str (:id-prefix root-spec) \"_\" i)}\n"
   "           (when extra {(keyword extra) i})\n"
   "           (into {} (map (fn [f] [(keyword f) \"v\"]) req)))))\n\n"
   "(defn seeded-store [n]\n"
   "  (let [st (m/fresh-store)]\n"
   "    (doseq [i (range n)] (m/persist! st (:entity root-spec) (seeded-row i)))\n"
   "    st))\n\n"
   "(println \"; store  (counts only)\")\n"
   "(let [e (:entity root-spec) p (:id-prefix root-spec)]\n"
   "  (row \"store 0\" (count (m/query (seeded-store 3) e)))\n"
   "  (row \"store 3\" (let [st (seeded-store 3)] (m/retract! st e (str p \"_1\"))\n"
   "                    (count (m/query st e))))\n"
   "  (row \"store 4\" (let [st (seeded-store 3)] (m/retract! st e \"nope\")\n"
   "                    (count (m/query st e))))\n"
   "  (row \"store 5\" (let [st (seeded-store 3)] (m/persist! st e (seeded-row 1))\n"
   "                    (count (m/query st e))))\n"
   "  (row \"store 7\" (count (m/query (seeded-store 3) (:entity other-spec)))))\n\n"
   "(println \"; table\")\n"
   "(doseq [i (range (count m/entity-specs))]\n"
   "  (row (str \"table \" i) (str-hash (table-line (nth m/entity-specs i)))))\n"))

(let [[repo-dir src-name] argv]
  (when-not (and repo-dir src-name)
    (refuse! "usage: <repo-dir> <src-dir-name>" {:argv argv}))
  (let [cljc (path/join repo-dir "src" src-name "main.cljc")]
    (when-not (fs/existsSync cljc) (refuse! "no oracle" {:path cljc}))
    (let [txt (fs/readFileSync cljc "utf8")
          ;; The harness calls these by name. Checked here rather than at load.
          ;; Matched on a WORD BOUNDARY, not a trailing space. Measured
          ;; 2026-09-11: the first version required "(defn page-limit " and
          ;; com-8th-wall writes the arglist on the next line, so a repository
          ;; that defines everything the harness needs was refused for not
          ;; defining it. A guard against an unloadable harness that instead
          ;; blocks a loadable one is the same defect pointed the other way.
          defined? (fn [v]
                     (boolean (re-find (re-pattern (str "\\(def(n)?\\s+"
                                                        (str/replace v "-" "\\-")
                                                        "[\\s\\n]"))
                                       txt)))
          missing (remove defined? required-vars)]
      (when (seq missing)
        (refuse! "the oracle does not define what the harness would call"
                 {:missing (vec missing) :oracle cljc}))
      (let [ns-name (str/replace src-name "_" "-")
            ;; The namespace the file DECLARES, which is not always the
            ;; directory with underscores turned into hyphens -- measured on
            ;; com-abb-robotics, whose ns is literally `abb_robotics.main`.
            declared (second (re-find #"\(ns\s+([A-Za-z0-9_.-]+)" txt))
            out (path/join repo-dir "q9-oracle.cljs")]
        (fs/writeFileSync out (harness (or declared (str ns-name ".main"))))
        (println (str "ORACLE\t" (or declared ns-name)))
        (println (str "WROTE\t" out "\t" (count (str/split-lines (harness (or declared ns-name)))) " lines"))))))
