(ns gen-case-tables
  "Writes `lang/compat/kotoba/string/case_tables.kotoba` from the JVM's own
  Character and String APIs.

    clojure -M scripts/gen_case_tables.clj

  WHY A GENERATOR AND NOT A HAND-WRITTEN TABLE. The whitespace predicate in
  `lang/compat/clojure/string.kotoba` is eleven ranges and was written out by
  hand. Case mapping is 1,488 lowercase and 1,505 uppercase code points, plus
  102 that `String.toUpperCase` expands to more than one character. A hand
  table of that size is a table of what someone believed Unicode says; this
  one is derived from the JVM the oracle then checks it against, and the
  generator is checked in so the derivation can be repeated when a JDK moves.

  WHY THE OUTPUT IS STRING LITERALS AND NOT ARITHMETIC. Kotoba has no
  code-point-to-string constructor -- `string-from-i64` writes a NUMBER in
  decimal, and every other string op takes a string apart rather than
  building a character. So a mapped character cannot be COMPUTED from its
  code point; it has to be present in the source. Each block below is one
  literal holding the mapped characters of a contiguous code-point range in
  order (unmapped code points inside the range carry themselves), indexed by
  `(* width (- point lo))`. A block is cut whenever the UTF-8 width of the
  targets changes or the next mapped code point is more than :max-gap away,
  so the literals stay proportional to what is actually mapped.

  WHY THE RANGE TEST IS `(if (>= p lo) (<= p hi) false)` AND NOT `(and ...)`.
  An unannotated `and` is i64, and a cond test position wants a bool. The
  nested form is the one measured to compile (2026-09-02, amu ca869d79e)."
  (:import (java.util Locale)))

(def ^:private out-path "lang/compat/kotoba/string/case_tables.kotoba")
(def ^:private max-gap 16)
(def ^:private code-points (range 0 0x110000))
(def ^:private surrogates (set (range 0xD800 0xE000)))

(defn- utf8-width [cp]
  (cond (< cp 0x80) 1 (< cp 0x800) 2 (< cp 0x10000) 3 :else 4))

(defn- one [cp] (String/valueOf (Character/toChars cp)))

(defn- blocks
  "Contiguous ranges of code points whose targets under `f` all have the same
  UTF-8 width, cut at a gap wider than `max-gap`. Surrogates are never spanned:
  they are not scalar values and could not be written into a literal."
  [f]
  (let [changed (vec (remove surrogates (filter #(not= % (f (int %))) code-points)))]
    (loop [cs changed out []]
      (if (empty? cs)
        out
        (let [lo (first cs)
              width (utf8-width (f (int lo)))
              extendable? (fn [prev c]
                            (and (<= (- c prev) max-gap)
                                 (not-any? #(or (surrogates %)
                                                (not= width (utf8-width (f (int %)))))
                                           (range (inc prev) (inc c)))))
              hi (loop [prev lo remaining (next cs)]
                   (let [c (first remaining)]
                     (if (and c (extendable? prev c))
                       (recur c (next remaining))
                       prev)))]
          (recur (drop-while #(<= % hi) cs)
                 (conj out {:lo lo :hi hi :width width
                            :literal (apply str (map #(one (f (int %))) (range lo (inc hi))))})))))))

(defn- special-uppercase
  "The code points where `String.toUpperCase(Locale.ROOT)` is not the
  one-character `Character.toUpperCase`. SpecialCasing.txt's unconditional
  entries, read off the JVM rather than off the file."
  []
  (for [cp code-points
        :when (not (surrogates cp))
        :let [expanded (.toUpperCase (one cp) Locale/ROOT)]
        :when (not= expanded (one (Character/toUpperCase (int cp))))]
    {:point cp :string expanded}))

(defn- clause [{:keys [lo hi width literal]}]
  (str "      (if (>= point " lo ") (<= point " hi ") false)\n"
       "      (string-substring " (pr-str literal)
       " (* " width " (- point " lo ")) (* " width " (+ 1 (- point " lo "))))\n"))

(defn- slice-fn [name- doc blocks-]
  (str ";; " doc "\n"
       ";; " (count blocks-) " blocks, "
       (reduce + (map (comp count #(.getBytes ^String % "UTF-8") :literal) blocks-))
       " literal bytes.\n"
       "(defn " name- " [s :string index :i64 width :i64] :string\n"
       "  (let [point (string-code-point-at s index)]\n"
       "    (cond\n"
       (apply str (map clause blocks-))
       "      :else (string-substring s index (+ index width)))))\n"))

(defn -main [& _]
  (let [lower (blocks #(Character/toLowerCase ^int %))
        upper (blocks #(Character/toUpperCase ^int %))
        special (special-uppercase)
        source
        (str
";; GENERATED by scripts/gen_case_tables.clj. Do not edit.
;;
;; The Unicode case mappings the JVM has, as Kotoba data. Read off
;; java.lang.Character and java.lang.String at generation time and checked
;; against those same functions, code point by code point, in
;; test/kotoba/lang/kotoba_string_case_test.clj.
;;
;; A mapped character cannot be COMPUTED here: Kotoba has no
;; code-point-to-string constructor (`string-from-i64` writes a number in
;; decimal). So each block is a literal holding the mapped characters of a
;; contiguous range in order -- code points inside the range that map to
;; themselves carry themselves -- indexed by `(* width (- point lo))`. Every
;; character in one block has the same UTF-8 width, which is what makes the
;; index arithmetic exact; a block is cut where the width changes.
;;
;; Each function answers for ONE code point and takes the string it came out
;; of, because a code point that is not in any table has to be returned as
;; itself and the only way to produce it is to slice the original bytes.
;;
;; Truth is a bool here, and the range test is spelled
;; `(if (>= point lo) (<= point hi) false)`: an unannotated `and` is i64 and
;; a cond test position wants a bool.
;;
;; Read off JDK " (System/getProperty "java.version") " on 2026-09-02. The Unicode
;; version is whatever that JDK carries; it is not asserted here, because a
;; version string proves nothing about a table. What IS checked is the mapping:
;; the oracle sweeps code points against these same JVM functions, so a JDK
;; that moves them turns the sweep red and this file is regenerated.

(ns kotoba.string.case-tables
  (:export [lower-slice upper-slice upper-root-slice]))

"
         (slice-fn "lower-slice"
                   "java.lang.Character.toLowerCase(int) -- the Unicode SIMPLE lowercase mapping, one code point to one code point."
                   lower)
         "\n"
         (slice-fn "upper-slice"
                   "java.lang.Character.toUpperCase(int) -- the Unicode SIMPLE uppercase mapping, one code point to one code point."
                   upper)
         "\n"
";; java.lang.String.toUpperCase(Locale.ROOT) differs from the simple mapping
;; at exactly " (count special) " code points, where it expands to more than one
;; character -- SpecialCasing.txt's unconditional entries. They are here as
;; whole literals rather than as an index, because the expansion is not one
;; character wide and there is nothing to index. Everything else falls
;; through to the simple table.
;;
;; There is no lower-root-slice. String.toLowerCase(Locale.ROOT) needs the
;; Final_Sigma condition, which is a property of the SURROUNDING string and
;; not of the code point; see lang/compat.edn :absent lower-case.
(defn upper-root-slice [s :string index :i64 width :i64] :string
  (let [point (string-code-point-at s index)]
    (cond\n"
         (apply str (for [{:keys [point string]} special]
                      (str "      (= point " point ") " (pr-str string) "\n")))
         "      :else (upper-slice s index width))))\n")]
    (spit out-path source)
    (println (str "WROTE\t" out-path
                  "\tlower-blocks=" (count lower)
                  "\tupper-blocks=" (count upper)
                  "\tspecial-upper=" (count special)
                  "\tbytes=" (count (.getBytes ^String source "UTF-8"))))))

(-main)
